# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-PBP
version:      0.00_01
version_from: lib/Acme/PBP.pm
installdirs:  site
requires:
    Module::Loaded:                0
    Perl::Critic:                  0
    Perl::Tidy:                    0
    PPI:                           0
    Smart::Comments:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
